// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SGS.OAD.DB.API.Models;

public partial class SGSLims_chemContext : DbContext
{
    public SGSLims_chemContext(DbContextOptions<SGSLims_chemContext> options)
        : base(options)
    {
    }

    public virtual DbSet<SQLEncryptPassword> SQLEncryptPasswords { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Chinese_Taiwan_Stroke_CI_AS");

        modelBuilder.Entity<SQLEncryptPassword>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("SQLEncryptPassword");

            entity.Property(e => e.DatabaseName).HasMaxLength(50);
            entity.Property(e => e.DatabaseRole).HasMaxLength(50);
            entity.Property(e => e.EncryptedId).HasMaxLength(200);
            entity.Property(e => e.EncryptedPassword).HasMaxLength(200);
            entity.Property(e => e.ID).HasMaxLength(200);
            entity.Property(e => e.PLanguage).HasMaxLength(20);
            entity.Property(e => e.PW).HasMaxLength(200);
            entity.Property(e => e.PermissionUserId).HasMaxLength(200);
            entity.Property(e => e.ServerName).HasMaxLength(20);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}