// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGS.OAD.DB.API.Models;

public partial class SQLEncryptPassword
{
    public string PLanguage { get; set; }

    public string ServerName { get; set; }

    public string DatabaseName { get; set; }

    public string DatabaseRole { get; set; }

    public string ID { get; set; }

    public string PW { get; set; }

    public string EncryptedId { get; set; }

    public string EncryptedPassword { get; set; }

    public string PermissionUserId { get; set; }
}